<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    <!-- 应用程序信息 -->
    <ApplicationIcon>Assets/Icons/icon.ico</ApplicationIcon>
    <AssemblyName>LuckyLilliaDesktop</AssemblyName>
    <Product>Lucky Lillia Desktop</Product>
    <AssemblyTitle>Lucky Lillia Desktop</AssemblyTitle>
    <Description>幸运莉莉娅桌面端</Description>
    <Version>3.1.1</Version>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <!-- 发布配置（仅在发布时使用） -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <WindowsSupportedOSPlatformVersion>5.1</WindowsSupportedOSPlatformVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="LuckyLilliaDesktop.Tests\**" />
    <None Remove="LuckyLilliaDesktop.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.14" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.4.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.14" />
    <PackageReference Include="ReactiveUI" Version="23.2.28" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
    <PackageReference Include="StaticLink.Avalonia" Version="2.88.9-7151.10" />
    <PackageReference Include="StaticLink.Avalonia.Native" Version="11.3.14.1" />

    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />

    <PackageReference Include="Serilog" Version="4.3.1" />

    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.9" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="VC-LTL" Version="5.3.1" />
    <PackageReference Include="YY-Thunks" Version="1.2.1" />
  </ItemGroup>
</Project>
